name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use Python 3.9 (adjust as needed)

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx  # Install libGL for OpenGL support

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt  # Install your Python dependencies from requirements.txt

      - name: Run Streamlit app
        run: streamlit run your_app.py  # Replace with the path to your Streamlit app
